task: crafter_reward
steps: 1.01e6
env_num: 1
eval_episode_num: 10
action_repeat: 1
train_ratio: 512
time_limit: 1000

seed: ${seed}
device: ${device}

size: [64, 64]
encoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
decoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
