task: 'memorymaze_9x9'
steps: 1.001e8
env_num: 1
eval_episode_num: 10
action_repeat: 2
train_ratio: 512
time_limit: 4000

seed: ${seed}
device: ${device}

encoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
decoder:
  mlp_keys: '$^'
  cnn_keys: 'image'
